version: "2"
services:

  web:
    build: ./web
    ports:
      - 80:80
      - 3000:3000
    volumes:
      - ./src:/home/workspace
    tty: true
  ganache-cli:
    build: ./ganache-cli
    ports:
      - 7545:7545
    volumes:
      - ./src:/home/workspace
    tty: true
    networks:
      default:
        aliases:
          - local.ganache