version: "2"
services:

  web:
    build: ./web
    ports:
      - 80:80
      - 3000:3000
    volumes:
      - ./src:/home/workspace
    tty: true
  truffle:
    build: ./truffle
    ports:
      - 81:80
      - 3001:3000
      - 9545:9545
    volumes:
      - ./src:/home/workspace
    tty: true    
  geth:
    image: ethereum/client-go:v1.10.18
    entrypoint: "/bin/sh"
    ports:
      - "30303:30303"
      - "8545:8545"
    tty: true
    volumes:
      - ./geth:/geth